# -*- coding: utf-8 -*-
"""Bangla Chat Bot Old.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yvj-n1WAWYEmS_XFDFlFKWpPEuiB4iXn
"""

pip install googletrans==4.0.0rc1

from googletrans import Translator

text= "I am not inevitable"


Bengali= Translator()

out= Bengali.translate(text, dest='bn')

print(out.text)

!pip install bardapi

from bardapi import Bard
import os
import time

os.environ['_BARD_API_KEY']="XXXXXX"   #Enter your bard api key here

input_text = "কিভাবে মঙ্গল গ্রহ উপনিবেশ করা যায়?"

out0= Translator().translate(input_text, dest='en')


answer= Bard().get_answer(out0.text)['content']
#print(Bard().get_answer(input_text)['content'])



out= Translator().translate(answer, dest='bn')

print(out.text)